// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naxpxkturladefrlyecs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5heHB4a3R1cmxhZGVmcmx5ZWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1ODg2OTIsImV4cCI6MjA1ODE2NDY5Mn0.Hq2k6C1LL6lB3qGeKKndHr356clB3UVA4yOPTKBey2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);